export const servData = [
      {id: 1, service: "Company Rubber Stamp", desc:"", price: 70, remarks: "active"},
      {id: 2, service: "Company Seal", desc:"", price: 150, remarks: "active"},
      {id: 3, service: "Notarisation on Documents", desc:"", price: 200, remarks: "active"},
      {id: 4, service: "Apostille on Documents", desc:"", price: 220, remarks: "active"},
      {id: 5, service: "Professional Directors", desc:"", price: 1100, remarks: "active"},
      {id: 6, service: "Professional Shareholders", desc:"", price: 1100, remarks: "active"},
      {id: 7, service: "Power(s) of Attorney", desc:"", price: 250, remarks: "active"},
      {id: 8, service: "Notarisation and Apostille on Documents", desc:"", price: 300, remarks: "active"},
      {id: 10, service: "Company Secretary", desc:"", price: 790, remarks: "active"},
      {id: 11, service: "VAT number", desc:"", price: 1000, remarks: "active"},
      {id: 12, service: "EIN & Physical Address", desc:"Employer Identification Number ($790.00) + Physical Address ($1580.00)", price: 2370, remarks: "active"},
      {id: 13, service: "Visual Branding Pack", desc:"(Company Logo + Business Card +  Letter Head)", price: 400, remarks: "active"},
      {id: 14, service: "Website Pack", desc:"(1 Year Website Domain + 1 Year Website Hosting +  One Page Website Building)", price: 1000, remarks: "active"},
      {id: 15, service: "1mo. Digital Marketing Support", desc:"", price: 300, remarks: "active"},
      {id: 16, service: "3mo. Digital Marketing Support", desc:"", price: 750, remarks: "active"},
      {id: 17, service: "6mo. Digital Marketing Support", desc:"", price: 1500, remarks: "active"},
      {id: 18, service: "12mo. Digital Marketing Support", desc:"", price: 3000, remarks: "active"},
      {id: 19, service: "International Courier", desc:"", price: 90, remarks: "active"},
      {id: 20, service: "Creation of Company Logo; Business Card; and Letter Head", desc:"", price: 200, remarks: "active"},
  ];