export const servData = [
    {id: 1, service: "Company Rubber Stamp", desc:"", price: 70, remarks: "active"},
    {id: 2, service: "Company Seal", desc:"", price: 150, remarks: "active"},
    {id: 3, service: "Notarisation on Documents", desc:"", price: 200, remarks: "active"},
    {id: 4, service: "Apostille on Documents", desc:"", price: 220, remarks: "active"},
    {id: 5, service: "Nominee Director", desc:"", price: 550, remarks: "active"},
    {id: 6, service: "Nominee Shareholder", desc:"", price: 550, remarks: "active"},
    {id: 7, service: "Power(s) of Attorney", desc:"", price: 200, remarks: "active"},
    {id: 8, service: "International Courier", desc:"", price: 80, remarks: "active"},
    {id: 9, service: "TIN number", desc:"", price: 250, remarks: "active"},
    {id: 10, service: "Visual Branding Pack", desc:"(Company Logo + Business Card +  Letter Head)", price: 250, remarks: "active"},
    {id: 11, service: "Website Pack", desc:"(1 Year Website Domain + 1 Year Website Hosting +  One Page Website Building)", price: 500, remarks: "active"},
    {id: 12, service: "1mo. Digital Marketing Support", desc:"", price: 150, remarks: "active"},
    {id: 13, service: "3mo. Digital Marketing Support", desc:"", price: 380, remarks: "active"},
    {id: 14, service: "6mo. Digital Marketing Support", desc:"", price: 720, remarks: "active"},
    {id: 15, service: "12mo. Digital Marketing Support", desc:"", price: 1350, remarks: "active"},
  ];